apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: backend-ms
spec:
  params:
  - name: git-repo-url
    value: https://github.com/$(body.repository.full_name).git
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)
