apiVersion: v1
kind: Service
metadata:
  labels:
    app: pnb-devops
  name: pnb-devops
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pnb-devops